controller:
  installPlugins:
    - kubernetes:4253.v7700d91739e5
    - kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
    - git:5.2.2
    - configuration-as-code:1810.v9b_c30a_249a_4c
    - bitbucket:241.v6d24a_57f9359
    - aws-codecommit-jobs:0.3.0
    - gitlab-plugin:1.8.1
    - github:1.39.0
    - slack:722.vd07f1ea_7ff40
    - prometheus:773.v3b_62d8178eec
    - cloudbees-disk-usage-simple:203.v3f46a_7462b_1a_
    - workflow-aggregator:600.vb_57cdd26fdd7
    - dependency-check-jenkins-plugin:5.5.0
  resources:
    limits:
      cpu: 1000m
      memory: 2.5Gi
    requests:
      cpu: 100m
      memory: 1300Mi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "Addons-Services"
              operator: In
              values:
              - "true"
